### PR TITLE
Gnome 45 port

### PR DESCRIPTION
**Pull request by BlankParticle**
This PR would be merged once we get some more testing done.

## TODO List
- [x] feat: Use ESM imports
- [x] ~fix: Doesn't check if `bluetoothctl` is available before trying to connect to a device, thus gets stuck in `Wait` state~
- [x] fix: Respect Debug Settings while logging
- [x] feat: Drop Legacy Bluetooth Support as all changes are non backwards compatible
- [x] fix: Device list doesn't update immediately after a devices is removed from paired devices
- [x] feat: Use built-in methods in favour of removing power.js and `bluetoothctl` dependency

### CODE REVIEW

**Comment by BlankParticle** [comment]
@ionutbortis, as said by people on Gnome Matrix Server, we may need to publish a fork with new uuid, what uuid do you want?

**Comment by ionutbortis** [comment]
> @ionutbortis, as said by people on Gnome Matrix Server, we may need to publish a fork with new uuid, what uuid do you want?
> 
> Edit: I am using `bluetooth-quick-connect@extensions.valhalla.gmail.com`, we can change it later if you want

The new UUID is fine by me. I'm trying now to send an email to `bjarosze@gmail.com`, hopefully we'll get a reply. So I would wait a couple of days until submitting a different extension to ego.

What do you think? 
Even if get a reply sometime, we could inactivate the new extension and just maintain the current one, I guess.

**Comment by BlankParticle** [comment]
I am making a clean up commit with the new UUID and formatting changes, if we can contact him I will revert the UUID change

**Comment by BlankParticle** [comment]
We got contacted with the original dev, he agreed to transfer ownership on EGO, but he archived his repo with a mention to our fork.
I have reverted the UUID change and we can merge this PR once we get the ownership and get the extension reviewed.

**Comment by BlankParticle** [comment]
New Version published on EGO! :tada:
Merging the PR

**Comment by ionutbortis** [comment]
Awesome work!

**Pull request merged**
