### PR TITLE
Add Russian Language

### PR DESCRIPTION
**Pull request by a1ex-ak**

### CODE REVIEW

**Comment by BlankParticle** [comment]
Hey, thanks for the russian language translations. Appreciate your effort.

As we are not going to support older versions you will find your translations in Gnome 45 version only.

**Comment by a1ex-ak** [comment]
It’s a shame that only Gnome has 45, but I’m still glad. Thank you.

**Comment by BlankParticle** [comment]
> It’s a shame that only Gnome has 45, but I’m still glad. Thank you.

I can compile a Gnome 43 verison for your, but will not be updated at extension.gnome.org.

You will need to install the zip manually, do you want me to do it?

**Comment by a1ex-ak** [comment]
I would be very grateful. Thank you

**Pull request merged**
